name: json_serializable_ioc
description: json_serializable_ioc simplifies the serialization and deserialization of models by encapsulating toJson and fromJson methods in a container. It allows developers to register converters and factories for any model, enabling the dynamic use of these methods without knowing their exact names.
version: 1.0.0
repository: https://github.com/melWiss/factory_converter_ioc

environment:
  sdk: ^3.4.3


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
