name: json_ioc_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  json_serializable_ioc:
    path: ../json_serializable_ioc
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable_ioc_generator:
    path: ../json_serializable_ioc_generator
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
