name: json_ioc_example
description: A sample command-line application to demonstrate the usage of json_serializable_ioc and json_serializable_ioc_generator.
version: 1.0.0
repository: https://github.com/melWiss/factory_converter_ioc

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  json_serializable_ioc: 1.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable_ioc_generator: 1.0.0
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
