name: json_serializable_ioc_generator
description: json_serializable_ioc_generator simplifies the registration of toJson and fromJson methods for models annotated with @JsonSerializable. This package works in conjunction with json_serializable_ioc to automatically generate the registration method.
version: 1.0.3
repository: https://github.com/melWiss/factory_converter_ioc

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  analyzer: ^5.13.0
  build: ^2.4.1
  source_gen: ^1.5.0
  json_serializable_ioc: ^1.0.0
  glob: ^2.1.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  lints: ^3.0.0
